### ISSUE TITLE
!qyt/!qytdl commands are inconsistent

### ISSUE THREAD

**Issue by rtrind** [Sinusbot/scripts#14]
Just updated my bot sinusbot-commands.js to enjoy some of the new commands and it was very promising. But while testing it, the qyt/qytdl command works 1 in 10 times.

On the logs the file seems to be downloaded correctly using the youtube-dl, and it shows on the queue on the web GUI list, waiting to play. When it should start playing, it simply does nothing (which is similar to the logs when the play works):

```
2020-04-20T23:35:44+00:00 Playing next from queue:
2020-04-20T23:35:35+00:00 [sinusbot-commands:165:16] Downloaded YouTube Video: https://www.youtube.com/watch?v=ZmUENUZx2w0
```

Latest version for the bot (1.0.0-beta.10-202ee4d) on Debian 10, latest version of the script (1.1.2) as well.
Trying to play the songs immediately using !yt works perfectly, but since our channel is a jukebox style, we prefer the commands which do not interrupt the current song.
 
Reverting to previous version of the sinusbot-commands.js (1.0.0) embedded on the bot release solves the issue, meaning the problem is probably on this file, but just by looking at the differences I could not understand the root cause. Updating the command.js library did no changes to the problem.

Let me know what else I need to supply in case the problem can't be reproduced easily and thanks for the awesome work!

**Comment by irgendwr** [comment]
Hi, thanks for submitting the issue, however I can't reproduce this, it works fine for me.

If I had to guess I would say that this is probably caused by YouTube's random DRM crap that causes issues for youtube-dl at the moment (https://github.com/ytdl-org/youtube-dl/issues/24713 & etc.), a lot of people are having random/not-always-reproducible problems with youtube-dl at the moment.

Did you try [clearing the signature cache of youtube-dl](https://sinusbot.github.io/docs/youtube-dl/#error-403)?

> Reverting to previous version of the sinusbot-commands.js (1.0.0) embedded on the bot release solves the issue

I find that hard to believe since the functionality has not changed and the script just tells the SinusBot to enqueue, so the functionality is built-in and not handled by the script.

> Let me know what else I need to supply in case the problem can't be reproduced easily and thanks for the awesome work!

Try clearing the signature cache (see above), if that doesn't change anything:
- What is your youtube-dl version? (should be the latest, just want to make sure)
- Where are you testing this? TS3 or Discord?
- Provide a step-by-step guide to reproduce (as detailed as possible!)
- Provide the full instance **and bot log**

### Steps to (not) reproduce

```
=> nothing is playing at the start
!qyt <https://www.youtube.com/watch?v=ZmUENUZx2w0>
=> bot starts playing
!qyt <https://www.youtube.com/watch?v=XYeuvbhKy4I>
!next
=> bot starts playing next song
```

### Information
`!version`
```
SinusBot v1.0.0-beta.11-6e0f00d on linux
sinusbot-commands.js v1.1.2
command.js v1.4.3
```
`youtube-dl --version`
```
youtube-dl 2020.03.24
```

**Comment by rtrind** [comment]
You were right. I was also skeptical about the script version having any relation with the issue (since the enqueue function was from the bot itself, not the script). It was probably just a big coincidence and my sample size not near enough to confirm the behavior. After removing the youtube-dl cache the behavior seems to became normal again.

Thanks for the quick response.
